version: 0.0
os: linux
files:
  - source: app/
    destination: /var/www/html
  - source: inc/
    destination: /var/www/inc
hooks:
  ApplicationStart:
    - location: deploy_hooks/start_service.sh
      runas: root
  ApplicationStop:
    - location: deploy_hooks/stop_service.sh
      runas: root
  ValidateService:
    - location: deploy_hooks/verify_service.sh
      runas: root